# Server packages installation

- name: Install custom packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
    force: yes
  with_items:
    - emacs-nox
    - gdal-bin
  become: yes
