# Server packages installation

- name: Install custom packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
  with_items:
    - git
    - emacs23-nox
    - gdal-bin
