- hosts: all
  sudo: yes

  vars:
    SERVER_SCRIPT: scripts/server-customize.sh

  tasks:
    # Customize GIS.lab Server
    - name: Copy customization script to server
      copy: src={{ SERVER_SCRIPT }}
            dest=/tmp/customize.sh
            owner=root group=root mode=0755

    - name: Copy QGIS customization to server
      copy: src=files/QGIS2.conf
            dest=/opt/gislab/system/accounts/skel/.config/QGIS
            owner=root group=root mode=0655

    - name: Run customization script on server
      shell: /tmp/customize.sh

    - name: Remove customization script from server
      file: path=/tmp/customize.sh
            state=absent
