# Perform GIS.lab customization for GISMentors

- hosts: all
  become: yes

  vars:
    # service-data-db
    dbname: gismentors
    home_dir: /mnt/home/gislab
    data_dir: /mnt/repository/gismentors
    # service-data-grass
    repository_grassdata: /mnt/repository/grassdata
    user_grassdata: /opt/gislab/system/accounts/skel/grassdata
    data_url: http://training.gismentors.eu/geodata/grass
    config_dir: /opt/gislab/system/accounts/skel/.grass7
    grass_location: gismentors
    # client
    root_dir: /opt/gislab/system/clients/desktop/root

  roles:
    #- { role: server-firewall, tags: ['server-firewall'] }
    - { role: server-accounts, tags: ['server-accounts'] }
    - { role: server-data-cleanup, tags: ['server-data-cleanup'] }
    - { role: server-data-db, tags: ['server-data-db']}
    - { role: server-data-grass, tags: ['server-data-grass'] }
    - { role: server-data-other, tags: ['server-data-other'] }
    - { role: client-desktop, tags: ['client-desktop'] }
    - { role: client-packages, tags: ['client-packages'] }
    - { role: client-nvidia, tags: ['client-nvidia'],
        when: NVIDIA }
    - { role: client-image, tags: ['client-image'] }
    - { role: user-accounts, tags: ['user-accounts'] }
    - { role: customization-done, tags: ['customization-done'] }
