- hosts: all
  sudo: yes

  vars:
    SERVER_SCRIPT: scripts/server-compile.sh

  tasks:
    # Compile GRASS 7.2 + GDAL 2.0 + QGIS 2.14 on server
    - name: Copy build script to server
      copy: src={{ SERVER_SCRIPT }}
            dest=/tmp/compile.sh
            owner=root group=root mode=0755

    - name: Run compilation
      shell: /tmp/compile.sh

    - name: Remove build script from server
      file: path=/tmp/compile.sh
            state=absent

    # - name: Rebuild client image
    #   shell: gislab-client-image
    #   #      when: lookup('env','GISLAB_GRASS_IMAGE') == 'yes'
    #   tags:
    #     - image
