- hosts: all
  sudo: yes

  vars:
    SERVER_SCRIPT: scripts/server-customize.sh

  tasks:
    - name: Copy QGIS customization to server
      copy: src=files/QGIS2.conf
            dest=/opt/gislab/system/accounts/skel/.config/QGIS
            owner=root group=root mode=0655
