# Install Nvidia drivers on client

- name: Check if we are running GIS.lab Unit
  shell: grep GISLAB_UNIQUE_ID /etc/gislab_version
  register: gislab_unit
  changed_when: no

- name: Add Graphics Drivers PPA repository
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    add-apt-repository -y ppa:graphics-drivers/ppa 

- name: Install nvidia packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} install nvidia-driver-525
  args:
    executable: /bin/bash
  when:
    gislab_unit.rc == 0
