# Install Nvidia drivers on client

- name: Check if we are running GIS.lab Unit
  shell: grep GISLAB_UNIQUE_ID /etc/gislab_version
  register: gislab_unit
  changed_when: no

- name: Install software-properties-common package
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt {{ apt_get_opts }} install {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - software-properties-common
  when:
    gislab_unit.rc == 0

- name: Add Graphics Drivers PPA repository
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    add-apt-repository --update --yes ppa:graphics-drivers/ppa
  when:
    gislab_unit.rc == 0

- name: Install nvidia packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt {{ apt_get_opts }} install {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - nvidia-396
  when:
    gislab_unit.rc == 0
