# User accounts customization

- name: Copy after-add (db) script to server
  template:
    src: after-add/db.j2
    dest: /opt/gislab/custom/accounts/after-add/db
    owner: root
    group: root
    mode: 0755

- name: Copy after-add (ssh-key) script to server
  template:
    src: after-add/ssh-key.j2
    dest: /opt/gislab/custom/accounts/after-add/ssh-key
    owner: root
    group: root
    mode: 0755

- name: Copy before-delete script to server
  template:
    src: before-delete/db.j2
    dest: /opt/gislab/custom/accounts/before-delete/db
    owner: root
    group: root
    mode: 0755

- name: Create QGIS config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/gislab/custom/accounts/files/.local/share/QGIS/QGIS3/profiles/default/QGIS

- name: QGIS3 desktop customization
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0655
  with_items:
    - {
    src: config/QGIS/QGIS3.j2,
    dst: /opt/gislab/custom/accounts/files/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
    }

- name: Check if grassdata exists
  stat:
    path: /opt/gislab/system/accounts/skel/.grassdata
  register: grassdata_stat

- name: Rename grassdata directory
  command: mv /opt/gislab/system/accounts/skel/.grassdata /opt/gislab/system/accounts/skel/grassdata
  when: grassdata_stat.stat.exists

- name: Update grassdata rc file
  replace:
    dest: "{{ grass_config_dir }}/rc"
    regexp: '\.grassdata'
    replace: 'grassdata'
  when: grassdata_stat.stat.exists
