# User accounts customization

- name: Copy after-add (db) script to server
  template:
    src: after-add/db.j2
    dest: /opt/gislab/custom/accounts/after-add/db
    owner: root
    group: root
    mode: 0755

- name: Copy after-add (ssh-key) script to server
  template:
    src: after-add/ssh-key.j2
    dest: /opt/gislab/custom/accounts/after-add/ssh-key
    owner: root
    group: root
    mode: 0755

- name: Copy before-delete script to server
  template:
    src: before-delete/db.j2
    dest: /opt/gislab/custom/accounts/before-delete/db
    owner: root
    group: root
    mode: 0755

- name: Create QGIS config directory
  file:
    path: /opt/gislab/custom/accounts/files/.config/QGIS
    state: directory

- name: QGIS desktop customization
  template:
    src: config/QGIS/QGIS2.j2
    dest: /opt/gislab/custom/accounts/files/.config/QGIS/QGIS2.conf
    owner: root
    group: root
    mode: 0655

- name: Download VFK plugin
  git:
    repo: https://github.com/ctu-geoforall-lab/qgis-vfk-plugin.git
    dest: /opt/gislab/system/accounts/skel/.qgis2/python/plugins/qgis-vfk-plugin-release-2_0
    version: release-2_0

- name: Download RUIAN plugin
  git:
    repo: https://github.com/ctu-geoforall-lab/qgis-ruian-plugin.git
    dest: /opt/gislab/system/accounts/skel/.qgis2/python/plugins/qgis-ruian-plugin-master

- name: Download GDAL-VFR library
  git:
    repo: https://github.com/ctu-geoforall-lab/gdal-vfr.git
    dest: /opt/gislab/system/accounts/skel/.qgis2/python/plugins/qgis-ruian-plugin-master/gdal_vfr

- name: Clone gislab-web repository
  git:
    repo: https://github.com/gislab-npo/gislab-web.git
    dest: "/home/{{ ansible_user }}/gislab-web"
  tags: ['gislab-web']

- name: Copy GIS.lab Web plugin
  command: cp -r "/home/{{ ansible_user }}/gislab-web/qgis/gislab_web" .
  args:
    chdir: /opt/gislab/system/accounts/skel/.qgis2/python/plugins/
    creates: gislab_web
  tags: ['gislab-web']

- name: Check if grassdata exists
  stat:
    path: /opt/gislab/system/accounts/skel/.grassdata
  register: grassdata_stat

- name: Rename grassdata directory
  command: mv /opt/gislab/system/accounts/skel/.grassdata /opt/gislab/system/accounts/skel/grassdata
  when: grassdata_stat.stat.exists

- name: Update grassdata rc file
  replace:
    dest: /opt/gislab/system/accounts/skel/.grass7/rc
    regexp: '\.grassdata'
    replace: 'grassdata'
  when: grassdata_stat.stat.exists
