# Client packages installation

- name: Install custom packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt-get update
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} install {{ packages|join(' ') }}
  args:
    executable: /bin/bash

- name: Install Rasterio, Shapely, OWSLib, Fiona
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    pip install {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - rasterio
    - shapely
    - OWSLib
    - Fiona

- name: Remove unused packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} autoremove
  args:
    executable: /bin/bash
