# Client packages installation

- name: Install custom GIS packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt update
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} install {{ packages|join(' ') }}
  args:
    executable: /bin/bash

- name: Install r-base package and dependecies
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} install {{ packages_stats|join(' ') }}
  args:
    executable: /bin/bash
  tags: ['client-packages-stats']

- name: Download rstudio package
  get_url:
    url: "{{ rstudio_url }}/{{ rstudio_pkg }}"
    dest: "{{ root_dir }}/var/cache/apt/archives/{{ rstudio_pkg }}"
    force: no
  tags: ['client-packages-stats']

- name: Install rstudio package
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} install /var/cache/apt/archives/{{ rstudio_pkg }}
  args:
    executable: /bin/bash
  tags: ['client-packages-stats']

- name: Install R packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    /usr/bin/Rscript --slave --no-save --no-restore-history
    -e "if (! ('{{ item }}' %in% installed.packages()[,'Package']))
    install.packages(pkgs='{{ item }}', repos=c('https://cloud.r-project.org/'))"
  with_items:
    - sp
    - maptools
    - classInt
    - RColorBrewer
    - lattice
    - rgdal
    - maps
    - raster
    - gstat
    - rgeos
    - OpenStreetMap
  args:
    executable: /bin/bash
  tags: ['client-packages-stats']

- name: Download GeoServer executable
  get_url:
#    url: http://sourceforge.net/projects/geoserver/files/GeoServer/2.16.5/geoserver-2.16.5-bin.zip
    url: https://training.gismentors.eu/gislab-packages/geoserver-2.16.5-bin.zip
    dest: /mnt/repository/gismentors

- name: Remove unused packages
  shell: >
    export DEBIAN_FRONTEND=noninteractive
    &&
    chroot {{ root_dir }}
    apt-get {{ apt_get_opts }} autoremove
  args:
    executable: /bin/bash
