# Client packages installation

- name: Install custom packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
  with_items:
    - gedit
    - geany
    - sqlitebrowser
    - python-pip
    - g++
    - python-dev
    - libgdal-dev
    - python-numpy
    - python-rpy2
    - ipython-notebook
    - python-tk
    - postgis

- name: Install Fiona
  pip:
    name: Fiona
    version: 1.6.4

- name: Install other pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - rasterio
    - shapely
    - OWSLib

- name: Add gismentors PPA repository
  apt_repository:
    repo: "ppa:landa-martin/gislab-testing"

- name: Install packages from gismentors PPA repository
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
  with_items:
    - qgis
    - python-qgis
    - qgis-plugin-grass

- name: Fix numpy version (for GRASS)
  pip:
    name: numpy
    version: 1.8

- name: Remove unused packages
  apt:
    autoremove: true
